# Start with Oracle Java 8 on Centos 7
FROM corvis/java8:latest
MAINTAINER Gregory Grubbs <gregoryg@cloudera.com>

#Add the CDH Yum repo
RUN wget http://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo
    sudo mv -v cloudera-cdh5.repo /etc/yum.repos.d/
    sudo yum -y makecache
    
# Install gateway packages
RUN sudo yum -y install pig hive spark-worker hadoop-client

#Copy config files - these are generated by Cloudera Manager in CM/CDH environments
COPY conf/core-site.xml /etc/hadoop/conf/core-site.xml
COPY conf/hadoop-env.sh /etc/hadoop/conf/hadoop-env.sh
COPY conf/hdfs-site.xml /etc/hadoop/conf/hdfs-site.xml
COPY conf/mapred-site.xml /etc/hadoop/conf/mapred-site.xml
COPY conf/mapred-site.xml /etc/hadoop/conf/ssl-client.xml
COPY conf/yarn-site.xml /etc/hadoop/conf/yarn-site.xml

# #copy kdc configs 
# COPY conf/krb5.conf /etc/krb5.conf
# COPY conf/kdc.conf /etc/krb5kdc/kdc.conf
# COPY data/principal /etc/krb5kdc/principal
# COPY data/principal.kadm5 /etc/krb5kdc/principal.kadm5
# COPY data/principal.kadm5.lock /etc/krb5kdc/principal.kadm5.lock
# COPY data/principal.ok /etc/krb5kdc/principal.ok
# COPY data/stash /etc/krb5kdc/stash
# COPY scripts/init_krb.sh /usr/bin/init_krb.sh

RUN echo export TERM=xterm >> /etc/bash.bashrc

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    HADOOP_COMMON_HOME=/usr/lib/hadoop \
    HADOOP_HDFS_HOME=/usr/lib/hadoop-hdfs \
    HADOOP_MAPRED_HOME=/usr/lib/hadoop-mapreduce \
    HADOOP_YARN_HOME=/usr/lib/hadoop-yarn


CMD ["bash"]