## TODO: Set up beeline command using location of HiveServer2
# Start with Oracle Java 8 on Centos 7
FROM openshift/base-centos7
MAINTAINER Gregory Grubbs <gregoryg@cloudera.com>

# Install Oracle Java 8 - example only
RUN yum -y install 'http://archive.cloudera.com/director/redhat/7/x86_64/director/2.6.1/RPMS/x86_64/oracle-j2sdk1.8-1.8.0+update121-1.x86_64.rpm'
RUN update-alternatives --install /usr/bin/java java /usr/java/jdk1.8.0_121-cloudera/jre/bin/java 10
RUN update-alternatives --set java /usr/java/jdk1.8.0_121-cloudera/jre/bin/java

#Add the CDH Yum repo
RUN wget http://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo
RUN mv -v cloudera-cdh5.repo /etc/yum.repos.d/
RUN rpm --import $(grep gpgkey /etc/yum.repos.d/cloudera-cdh5.repo|cut -d'=' -f2|tr -d ' ')
RUN yum -y update
    
# Install gateway packages
RUN yum -y install hive spark-worker hadoop-client

#Copy config files - these are generated by Cloudera Manager in CM/CDH environments
RUN mkdir -p /etc/hadoop/conf-container
COPY conf/core-site.xml /etc/hadoop/conf-container/core-site.xml
COPY conf/hadoop-env.sh /etc/hadoop/conf-container/hadoop-env.sh
COPY conf/hdfs-site.xml /etc/hadoop/conf-container/hdfs-site.xml
COPY conf/mapred-site.xml /etc/hadoop/conf-container/mapred-site.xml
COPY conf/mapred-site.xml /etc/hadoop/conf-container/ssl-client.xml
COPY conf/yarn-site.xml /etc/hadoop/conf-container/yarn-site.xml
RUN update-alternatives --install /etc/hadoop/conf hadoop-conf /etc/hadoop/conf-container 10
RUN update-alternatives --set hadoop-conf /etc/hadoop/conf-container

# #copy kdc configs 
# COPY conf/krb5.conf /etc/krb5.conf
# COPY conf/kdc.conf /etc/krb5kdc/kdc.conf
# COPY data/principal /etc/krb5kdc/principal
# COPY data/principal.kadm5 /etc/krb5kdc/principal.kadm5
# COPY data/principal.kadm5.lock /etc/krb5kdc/principal.kadm5.lock
# COPY data/principal.ok /etc/krb5kdc/principal.ok
# COPY data/stash /etc/krb5kdc/stash
# COPY scripts/init_krb.sh /usr/bin/init_krb.sh

RUN echo export TERM=xterm >> /etc/bash.bashrc

# Set recommended values for gateways
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    HADOOP_COMMON_HOME=/usr/lib/hadoop \
    HADOOP_HDFS_HOME=/usr/lib/hadoop-hdfs \
    HADOOP_MAPRED_HOME=/usr/lib/hadoop-mapreduce \
    HADOOP_YARN_HOME=/usr/lib/hadoop-yarn


CMD ["bash"]